/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "Blog": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
    "CMS": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
    "Landing": {
      "type": "sst.aws.Astro"
      "url": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}